<div class="simplenews">
   <?php
		$block->getDreamProduct();
      $newsCollection = $block->getCollection();
      if ($newsCollection->getSize() > 0) :
   ?>
      <div class="toolbar top">
         <?php //echo $block->getPagerHtml(); ?>
      </div>
 
      <ul>
         <?php foreach ($newsCollection as $news) : ?>
            <li>
               <div class="simplenews-list">
                  <a class="news-title" href="<?php echo $this->getUrl('dream/index/view',
 ['id' => $news->getId()]) ?>"><?php echo $news->getTitle() ?></a>
                  <div class="simplenews-list-content">
                     <?php echo $news->getSummary() ?>
                  </div>
               </div>
            </li>
         <?php endforeach; ?>
      </ul>
 
      <div style="clear: both"></div>
 
      <div class="toolbar-bottom">
         <div class="toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
         </div>
      </div>
   <?php else : ?>
      <p><?php echo __('Have no article!') ?></p>
   <?php endif; ?>
   <input id="mai-uoc-kaka" type="text" name="test_uoc_mai" />
   Mai uoc zxcvzxvxcbxc
</div>
<script type="text/javascript">
    require(['jquery'],function($){
		$(document).ready(function(){
			$('#mai-uoc-kaka').click(function()
			{
				alert('User Jquery Lebraly');
			})
		})
    });
</script>